version: "3.9"
services:
  server:
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 20000:20000
    environment:
      - NODE_ENV=development
    mem_reservation: 128M
