version: "3.9"
services:
  server:
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 20000:20000
    environment:
      - NODE_ENV=development
    mem_reservation: 128M
    depends_on:
      - database
  database:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_DB_NAME}
    ports:
      - "5432:5432"
